// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129050234_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Went Hiking with Joe",
                            Created = new DateTime(2025, 11, 29, 18, 2, 33, 524, DateTimeKind.Local).AddTicks(9698),
                            Title = "Went to Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Went Hiking with Moe",
                            Created = new DateTime(2025, 11, 29, 18, 2, 33, 525, DateTimeKind.Local).AddTicks(47),
                            Title = "Came Back to Hiking"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Went Diving with Moe",
                            Created = new DateTime(2025, 11, 29, 18, 2, 33, 525, DateTimeKind.Local).AddTicks(52),
                            Title = "Came Back to Hiking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
